#org.gradle.jvmargs=-Xmx1536M
org.gradle.jvmargs=-Xmx16384m
# 显式指定 Gradle 使用 JDK 17
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
